### ISSUE TITLE
Copy Link to search results broken

### ISSUE THREAD

**Issue by mandrewj** [BioCache/NEON-Biorepository#20]
When copying the link from a search result page post normal specimen-search, the link does not copy correctly (i.e. with the search parameters saves).  For instance, I have searched for a subset of invertebrate bycatch:
<img width="1295" alt="Screen Shot 2019-08-22 at 10 24 41 AM" src="https://user-images.githubusercontent.com/6679254/63535774-14528880-c4c7-11e9-8f04-662ba2b693f2.png">

And the copied link simply gives the obscured link as this:

https://biorepo.neonscience.org/portal/collections/list.php#

**Comment by arbolitoloco** [comment]
Fixed (could not trace where/when it was fixed, though)
